config/routes.rb
IE2::Application.routes.draw do
  get "units/user_index"
  get "bills/pay"
  resources :messages

  resources :news

  resources :payments

  resources :bills

  resources :rates

  resources :plans

  resources :expenses

  resources :units
  resources :profiles
  resources :buildings

  get "charge/dashboard"
  get "charge/help"
  get "home/index"

  root 'home#index'

  devise_for :users, :controllers => { 
    :registrations => :registrations
  }

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :unit
	belongs_to :expense
	has_many :payments

	validates :price, presence: { :message => "ورود قیمت الزامی است." }, numericality: { only_integer: true }
	validates_presence_of :deadline, :message => "ورود تاریخ پایان الزامی است."
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bill, only: [:show, :edit, :update, :destroy]



  def pay
    @bill = Bill.find(params[:bill_id])
    if @bill.status == true
      @bill.status = false
    else
      @bill.status = true
    end
    @bill.save    
  end
  
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:expense_id, :unit_id, :price, :deadline, :description, :status)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expense_id %><br>
    <%= f.number_field :expense_id %>
  </div>
  <div class="field">
    <%= f.label :unit_id %><br>
    <%= f.number_field :unit_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h1>ویرایش قبض</h1>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-5">

					<%= render 'form' %>

					<%= link_to t('Show'), @bill, :class => 'btn btn-info' %>
					<%= link_to t('Back'), bills_path, :class => 'btn btn-orange' %>
				</div>
        <div class="col-md-7"></div>
      </div>
    </div>
  </div>
</div>

app/views/bills/index.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h1>Listing bills</h1>
    </div>
    <div class="panel-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Expense</th>
            <th>Unit</th>
            <th>Price</th>
            <th>Deadline</th>
            <th>Description</th>
            <th>Status</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @bills.each do |bill| %>
            <tr>
              <td><%= bill.expense_id %></td>
              <td><%= bill.unit_id %></td>
              <td><%= bill.price %></td>
              <td><%= bill.deadline %></td>
              <td><%= bill.description %></td>
              <td><%= bill.status %></td>
              <td><%= link_to 'Show', bill %></td>
              <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
              <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Bill', new_bill_path, :class => 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/bills/new.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h1>قبض جدید</h1>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-5">

					<%= render 'form' %>

					<%= link_to t('Back'), bills_path, :class => 'btn btn-orange' %>
				</div>
        <div class="col-md-7"></div>
      </div>
    </div>
  </div>
</div>

app/views/bills/pay.js.erb
<% if @bill.status == false %>
$("#bill_<%= @bill.id %>").html("پرداخت نشده");
<% else %>
$("#bill_<%= @bill.id %>").html("پرداخت شده");
<%end%>

app/views/bills/show.html.erb
<p>
  <strong>Expense:</strong>
  <%= @bill.expense_id %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @bill.unit_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bill.price %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @bill.deadline %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bill.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bill.status %>
</p>

<%= link_to t('Edit'), edit_bill_path(@bill), :class => 'btn btn-primary' %> |
<%= link_to t('Back'), bills_path, :class => 'btn btn-orange' %>