config/routes.rb
IE2::Application.routes.draw do
  get "units/user_index"
  get "bills/pay"
  resources :messages

  resources :news

  resources :payments

  resources :bills

  resources :rates

  resources :plans

  resources :expenses

  resources :units
  resources :profiles
  resources :buildings

  get "charge/dashboard"
  get "charge/help"
  get "home/index"

  root 'home#index'

  devise_for :users, :controllers => { 
    :registrations => :registrations
  }

  

end

app/models/building.rb
class Building < ActiveRecord::Base
	belongs_to :user
	has_many :units
	has_many :expenses
	has_many :plans
	has_many :messages
	has_many :news

	validates_presence_of :floor_cnt, numericality: { only_integer: true, :message => "ورود تعداد تبقات ساختمان الزامی است."}
	validates_presence_of :units_cnt, numericality: { only_integer: true, :message => "ورود تعداد واحد ساختمان الزامی است."}

	def name_of_building
		"#{name}"
    end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :ban_resident_area
  before_action :authenticate_user!
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    #@buildings = Building.all.where(:manager_id => current_user.id)
    # authorize! :index, @building
    @buildings = current_user.buildings
    if @buildings.size == 1
      @building = @buildings.first
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    if @building.user != current_user
      redirect_to '/'
    end
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    @building.user_id = current_user.id

    respond_to do |format|
      if @building.save
        format.html { redirect_to building_path(@building), notice: 'ساختمان با موفقیت ایجاد شد.' }
        format.json { render action: 'show', status: :created, location: @building }
      else
        format.html { render action: 'new' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'ساختمان با موفقیت به روزرسانی شد.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name,:floor_cnt, :units_cnt, :user_id, :general_info)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper


	def get_buildings
		@buildings = current_user.buildings
	end
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <!--h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2-->

      <div class='error_explanation'>
      <% @building.errors.each do |attr,msg| %>
        <%= msg %>
      <% end %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "نام ساختمان", :class => 'control-label'%>
    <div class="input-group">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :floor_cnt, "تعداد طبقات", :class => 'control-label'%>
    <div class="input-group">
      <%= f.number_field :floor_cnt, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :units_cnt, "تعداد واحد", :class => 'control-label' %>
    <div class="input-group">
      <%= f.number_field :units_cnt, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group hide">
    <%= f.label :user_id, "مدیر", :class => 'control-label' %>
    <div class="input-group">
      <%= f.number_field :user_id, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "تائید", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h3><% if @building.name != nil %>
          ویرایش <%= @building.name %>
          <% else %>
          ویرایش ساختمان
          <% end %></h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-5">

        <%= render 'form' %>
        <br/>
        <%= link_to building_path(@building),:class => "btn btn-orange" do %>
          <i class="fa fa-arrow-circle-o-right"></i>&nbsp;
          <%= t('Back') %>
        <% end %>

        <%= link_to @building, method: :delete, data: { confirm: 'آیا مطمئن هستید؟' },:class => "btn btn-danger" do %>
          <i class="fa fa-trash-o"></i>&nbsp;
          <%= 'حذف این ساختمان' %>
        <% end %>
      </div>
        <div class="col-sm-7"></div>
      </div>
    </div>
  </div>
</div>

app/views/buildings/index.html.erb
<div class="container">
  <div class="panel">
    <% if @buildings.size == 0 %>
    <div class="panel-heading">
      <h3>ساختمانی برای حساب شما موجود نیست</h3>
    </div>
    <div class="panel-body">
      <br>

      <%= link_to new_building_path,:class => "btn btn-primary" do %>
      <i class="fa fa-plus-square"></i>&nbsp;
      <%= 'ایجاد ساختمان جدید' %>
      <% end %>
    </div>
    <% elsif @buildings.size == 1 %>
    <% building = @buildings.first %>
    <div class="panel-heading">
      <h3><% if building.name != nil %>
          <%= building.name %>
          <% else %>
          <%= 'ساختمان شما' %>
          <% end %></h3>
    </div>
    <div class="panel-body">
      <br>
      <div class="row">
        <div class="col-sm-8">
          <table id="buildings-table">
            <thead>
              <tr>
                <th style="width=540px;"></th>
                <th style="width=30%;"></th>
              </tr>
            </thead>
            <tbody>

              <tr>
                <th><strong>نام ساختمان:</strong></th>
                <th><%= building.name %></th>
              </tr>
              <tr>
                <th><strong>تعداد طبقات:&nbsp;</strong></th>
                <th><%= building.floor_cnt %></th>
              </tr>

              <tr>
                <th><strong>تعداد واحد:</strong></th>
                <th><%= building.units_cnt %></th>
              </tr>
              <tr>
                <th><strong>نام مدیر:</strong></th>
                <th><%= @building.user.profile.first_name %> <%= @building.user.profile.last_name %></th>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-sm-4">
          <!-- Picture -->
        </div>
      </div>
      <div class="pull-left">
        <%= link_to building,:class => "btn btn-success" do %>
          <i class="fa fa-folder-open-o"></i>&nbsp;
          <%=t :show_building_info %>
        <% end %>
      </div>
      <br>
      <br/>

      <div class="row-fluid">
        <div class="table-responsive">
          <table class="table table-success table-condensed table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th style="width:10%;">شماره واحد</th>
                <th style="width:15%;">نام مالک</th>
                <th style="width:10%;">طبقه</th>
                <th style="width:15%;">جهت مکانی</th>
                <th style="width:15%;">مساحت</th>
                <th style="width:10%;">تعداد ساکنین</th>
              </tr>
            </thead>
            <tbody>
              <% @units = @building.units %>
              <% @units.each do |unit| %>
              <tr>
                <th><%= unit.unit_number %></th>
                <th><% if unit.user != nil and unit.user.profile != nil %>
                    <%= unit.user.profile.first_name %> <%= unit.user.profile.last_name %>
                    <% end %></th>
                <th><%= unit.floor_number %></th>
                <th><%= unit.side %></th>
                <th><%= unit.area %></th>
                <th><%= unit.resident_count %></th>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <div class="left">
        <%= link_to new_expense_path(building_id: building.id),:class => "btn btn-primary" do %>
          <i class="fa fa-plus-square"></i>&nbsp;
          <%= 'هزینه جدید برای این ساختمان' %>
        <% end %>
        <%= link_to expenses_path(building_id: building.id),:class => "btn btn-info" do %>
          <i class="fa fa-tasks"></i>&nbsp;
          <%= 'مشاهده هزینه ها' %>
        <% end %>
      </div>
    </div>
    <% else %>
    <div class="panel-heading">
      <h3>لیست ساختمانها</h3>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>نام ساختمان</th>
              <th style="width:10%;"></th>
              <th style="width:10%;"></th>
              <th style="width:10%;"></th>
            </tr>
          </thead>

          <tbody>
            <% @buildings.each do |building| %>
              <tr>
                <td><%= building.name %></td>
                <td>
                  <%= link_to building,:class => "btn btn-success" do %>
                  <i class="fa fa-folder-open-o"></i>&nbsp;
                  <%=t :show_building_info %>
                  <% end %>
                </td>
                <td>
                <%= link_to new_expense_path(building_id: building.id),:class => "btn btn-primary" do %>
                  <i class="fa fa-plus-square"></i>&nbsp;
                  <%= 'هزینه جدید برای این ساختمان' %>
                <% end %>
                </td>
                <td>
                <%= link_to expenses_path(building_id: building.id),:class => "btn btn-info" do %>
                  <i class="fa fa-tasks"></i>&nbsp;
                  <%= 'مشاهده هزینه ها' %>
                <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/buildings/new.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h1>ایجاد ساختمان</h1>
    </div>
    <div class="panel-body">
    	<div class="row">
    		<div class="col-sm-5">

          <%= render 'form' %>

          <br>
          <%= link_to buildings_path,:class => "btn btn-orange" do %>
          <i class="fa fa-arrow-circle-o-right"></i>&nbsp;
          <%= t('Back') %>
          <% end %>
        </div>
        <div class="col-sm-7"></div>
      </div>
    </div>
  </div>
</div>

app/views/buildings/show.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h3><% if @building.name != nil %>
        <%= @building.name %>
        <% else %>
        <%= 'اطلاعات ساختمان' %>
        <% end %></h3>
      </div>
      <div class="panel-body">
        <div class="row-fluid">
          <p>
            <strong>نام ساختمان:</strong>
            <%= @building.name %>
          </p>

          <p>
            <strong>تعداد طبقات:</strong>
            <%= @building.floor_cnt %>
          </p>

          <p>
            <strong>تعداد واحد:</strong>
            <%= @building.units_cnt %>
          </p>

          <p>
            <strong>نام مدیر:</strong>
            <%= @building.user.profile.first_name %> <%= @building.user.profile.last_name %>
          </p>
          <% if @building.units.size == 0 %>
          <%= link_to new_unit_path(building_id: @building.id),:class => "btn btn-primary" do %>
          <i class="fa fa-plus-square"></i>&nbsp;
          <%= 'واحد جدید برای این ساختمان' %>
          <% end %>
          <% end %>
          <br>
          <br>
          <div class="table-responsive">
            <table class="table table-success table-condensed table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th style="width:15%;">نام مالک</th>
                  <th style="width:8%;">طبقه</th>
                  <th style="width:8%;">شماره واحد</th>
                  <th style="width:15%;">جهت مکانی</th>
                  <th style="width:8%;">مساحت</th>
                  <th style="width:10%;">تعداد ساکنین</th>
                  <th style="width:8%;"></th>
                </tr>
              </thead>
              <tbody>
                <% @units = @building.units %>
                <% @units.each do |unit| %>
                <tr>
                  <th>
                    <% if unit.user != nil and unit.user.profile != nil %>
                    <%= unit.user.profile.first_name %> <%= unit.user.profile.last_name %>
                    <% end %>
                  </th>
                  <th><%= unit.floor_number %></th>
                  <th><%= unit.unit_number %></th>
                  <th><%= unit.side %></th>
                  <th><%= unit.area %></th>
                  <th><%= unit.resident_count %></th>
                  <th class="center">
                    <%= link_to edit_unit_path(unit), :class => 'btn btn-primary' do %>
                    <i class="fa fa-edit"></i>&nbsp;
                    <%= 'ویرایش واحد' %>
                    <% end %>
                  </th>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>              
        </div>
      </div>
      <div class="panel-footer">
        <div class="left">
          <%= link_to new_expense_path(building_id: @building.id),:class => "btn btn-primary" do %>
            <i class="fa fa-plus-square"></i>&nbsp;
            <%= 'هزینه جدید برای این ساختمان' %>
          <% end %>
          <%= link_to expenses_path(building_id: @building.id),:class => "btn btn-info" do %>
            <i class="fa fa-tasks"></i>&nbsp;
            <%= 'مشاهده هزینه ها' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>