config/routes.rb
IE2::Application.routes.draw do
  get "units/user_index"
  get "bills/pay"
  resources :messages

  resources :news

  resources :payments

  resources :bills

  resources :rates

  resources :plans

  resources :expenses

  resources :units
  resources :profiles
  resources :buildings

  get "charge/dashboard"
  get "charge/help"
  get "home/index"

  root 'home#index'

  devise_for :users, :controllers => { 
    :registrations => :registrations
  }

  

end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :rates
	belongs_to :building

	validates_presence_of :building_id
	validates_presence_of :name, :message => "ورود نام الزامی است."

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  before_action :ban_resident_area
  before_action :authenticate_user!
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @building_id = params[:building_id]
    @building = Building.find(@building_id)
    if(@building_id != nil)
      @plans = Plan.all.where(:building_id => @building_id)
    else
      @plans = Plan.all
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @building_id = @plan.building_id
    @building = Building.find(@building_id)
  end

  # GET /plans/new
  def new
    @plan = Plan.new
    @plan.building_id = params[:building_id]
    @building_id = params[:building_id]
    @building = Building.find(@building_id)
  end

  # GET /plans/1/edit
  def edit
    if(@plan.number == 0 or @plan.number == 1 or @plan.number == 2)
      redirect_to @plan, notice: 'امکان ویرایش این پلان موجود نیست.'
    end
    @building_id = @plan.building_id
    @building = Building.find(@building_id)
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    respond_to do |format|
      if @plan.save
        params.each do |name, value|
          if /unit_(.+)$/.match(name)
            Rate.create(:plan_id => @plan.id, :unit_id => $1, :rate => value)
          end
        end
        format.html { redirect_to plans_path(:building_id => @plan.building_id), notice: 'پلان هزینه با موفقیت ایجاد شد.' }
        format.json { render action: 'show', status: :created, location: @plan }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    params.each do |name, value|
      if /unit_(.+)$/.match(name)
        @rate = @plan.rates.where(:unit_id => $1).first
        if @rate != nil
          @rate.update(:plan_id => @plan.id, :unit_id => $1, :rate => value)
        else
          Rate.create(:plan_id => @plan.id, :unit_id => $1, :rate => value)
        end
      end
    end
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to plans_path(:building_id => @plan.building_id), notice: 'پلان هزینه با موفقیت به روز رسانی شد.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @building_id = @plan.building_id
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_path(:building_id => @building_id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:building_id, :name, :number)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group hidden">
    <%= f.label :building_id, :class => 'form-label' %>
    <%= f.number_field :building_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name,"نام", :class => 'form-label' %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :number,"شماره", :class => 'form-label' %>
    <%= f.number_field :number, :class => 'form-control' %>
  </div>
  <br/>
  <br/>
  <% @plan.building.units.each do |unit| %>
  <div class="form-group">
  <%= unit.id %>
  &nbsp;
  <%= number_field_tag "unit_#{unit.id}", 1 %>
  </div>
  <%end%>
  <div class="actions">
    <%= f.submit "تائید", :class => 'btn btn-success col-md-4' %>
  </div>
<% end %>

app/views/plans/_form_modal.html.erb
<%= form_for(@plan, :remote => true) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group hidden">
    <%= f.label :building_id, :class => 'form-label' %><br>
    <%= f.number_field :building_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name,"نام", :class => 'form-label' %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group hidden">
    <%= f.label :number,"شماره", :class => 'form-label' %><br>
    <%= f.number_field :number, :class => 'form-control' %>
  </div>
  <br/>
  <br/>
  <% @plan.building.units.each do |unit| %>
  <div class="form-group">
    واحد <%= unit.unit_number %>
    &nbsp;
    <% if @plan.rates.where(:unit_id => unit.id).first != nil and @plan.rates.where(:unit_id => unit.id).first.rate != nil %>
      <%= number_field_tag "unit_#{unit.id}", @plan.rates.where(:unit_id => unit.id).first.rate %>
    <% else %>
      <%= number_field_tag "unit_#{unit.id}", 1 %>
    <% end %>
  </div>
  <%end%>
  <div class="form-group">
    <%= f.submit "تائید", :class => 'btn btn-success col-sm-4' %>
    &nbsp;
    <button id="cancel" type="button" class="btn btn-default" data-dismiss="modal">انصراف</button>
  </div>
<% end %>

app/views/plans/_new_plan_item.html.erb
<div>
<%= radio_button_tag :plan_id, @plan.id %>
&nbsp;
<%= @plan.name %>
</div>

app/views/plans/_uform.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group hidden">
    <%= f.label :building_id, :class => 'form-label' %><br>
    <%= f.number_field :building_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name,"نام", :class => 'form-label' %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group hidden">
    <%= f.label :number,"شماره", :class => 'form-label' %><br>
    <%= f.number_field :number, :class => 'form-control' %>
  </div>
  <br/>
  <br/>
  <% @plan.building.units.each do |unit| %>
  <div class="form-group">
    واحد <%= unit.unit_number %>
    &nbsp;
    <% if @plan.rates.where(:unit_id => unit.id).first != nil and @plan.rates.where(:unit_id => unit.id).first.rate != nil %>
      <%= number_field_tag "unit_#{unit.id}", @plan.rates.where(:unit_id => unit.id).first.rate %>
    <% else %>
      <%= number_field_tag "unit_#{unit.id}", 1 %>
    <% end %>
  </div>
  <%end%>
  <div class="form-group">
    <%= f.submit "تائید", :class => 'btn btn-success col-sm-4' %>
  </div>
<% end %>
<br/>
<br/>

app/views/plans/create.js.erb
$('#newPlan').modal('hide');

$('#plan-choose').append("<%= escape_javascript(render(:partial => 'new_plan_item', :object => @plan)) %>");

$('#newPlan').find('input[type="text"],input[type="email"],textarea,select').val('');

$('.notification').show(500).html("پلان جدید ایجاد گردید.").delay(3000).hide(500);

app/views/plans/edit.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h3><% if @plan.building.name != nil %>
          ویرایش پلان هزینه برای <%= @plan.building.name %>
          <% else %>
          ویرایش پلان هزینه برای ساختمان
          <% end %></h3>
    </div>
    <div class="panel-body">
    	<div class="row">
    		<div class="col-sm-5">

				<%= render 'uform' %>

        <br/>
        <br/>
        <%= link_to plans_path(:building_id => @plan.building_id),:class => "btn btn-orange" do %>
          <i class="fa fa-arrow-circle-o-right"></i>&nbsp;
          <%= t('Back') %>
        <% end %>
        <%= link_to @plan, method: :delete, data: { confirm: 'آیا اطمینان دارید؟' },:class => "btn btn-danger" do %>
          <i class="fa fa-trash-o"></i>&nbsp;
          <%= 'حذف این پلان هزینه' %>
        <% end %>

			</div>
    		<div class="col-sm-7"></div>
    	</div>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h3><% if @building.name != nil %>
        لیست پلان های هزینه <%= @building.name %>
        <% else %>
        لیسته پلان های هزینه ساختمان
        <% end %></h3>
      </div>
      <div class="panel-body">
        <%= link_to new_plan_path(:building_id => @building_id),:class => "btn btn-primary" do %>
        <i class="fa fa-plus-square"></i>&nbsp;
        <%= 'پلان هزینه جدید برای این ساختمان' %>
        <% end %>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>ردیف</th>
                <th>نام</th>
                <% @building.units.each do |unit| %>
                <th>واحد <%= unit.unit_number %></th>
                <% end %>
                </tr>
              </thead>

              <tbody>
                <% @plans.each_with_index do |plan,index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= plan.name %></td>
                  <% @building.units.each do |unit| %>
                    <% if plan.rates.where(:unit_id => unit.id).first != nil %>
                    <td>
                    <%= plan.rates.where(:unit_id => unit.id).first.rate %>
                    </td>
                    <% else %>
                    <td>
                    <%= "موجود نیست" %>
                    </td>
                    <%end%>
                  <% end %>
                  <td>
                  <%= link_to plan, :class => 'btn btn-success' do %>
                    <i class="fa fa-folder-open-o"></i>&nbsp;
                    <%= 'نمایش جزئیات' %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

app/views/plans/new.html.erb
<div class="container">
  <div class="panel">
    <div class="panel-heading">
      <h3><% if @plan.building.name != nil %>
          ایجاد پلان هزینه برای <%= @plan.building.name %>
          <% else %>
          ایجاد پلان هزینه برای ساختمان
          <% end %></h3>
    </div>
    <div class="panel-body">
    	<div class="row">
    		<div class="col-sm-5">

				<%= render 'uform' %>
				<br/>
        <br/>
        <%= link_to plans_path(:building_id => @plan.building_id), :class => "btn btn-orange" do %>
          <i class="fa fa-arrow-circle-o-right"></i>&nbsp;
          <%= t('Back') %>
        <% end %>
			</div>
    		<div class="col-sm-7"></div>
    	</div>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<div class="container">
	<div class="panel">
		<div class="panel-heading">
		<h3>
          <%= @plan.name %></h3>
		</div>
		<div class="panel-body">
			<p>
				<strong>نام ساختمان:</strong>
				<%= @plan.building.name %>
			</p>

			<p>
				<strong>نام:</strong>
				<%= @plan.name %>
			</p>
			<br/>
			<p>
				<strong>ضرایب واحدها در این پلان</strong>
			</p>

			<% @plan.building.units.each do |unit| %>
			<div>
				واحد <%= unit.unit_number %> : 
				<% if @plan.rates.where(:unit_id => unit.id).first != nil %>
				<%= @plan.rates.where(:unit_id => unit.id).first.rate %>
				<% else %>
				<%= "موجود نیست" %>
				<%end%>
			</div>
			<%end%>

			<%= link_to plans_path(:building_id => @plan.building_id),:class => "btn btn-orange" do %>
			<i class="fa fa-arrow-circle-o-right"></i>&nbsp;
			<%= t('Back') %>
			<% end %>

			<%= link_to edit_plan_path(@plan), :class => 'btn btn-primary' do %>
			<i class="fa fa-edit"></i>&nbsp;
			<%= 'ویرایش پلان هزینه' %>
			<% end %>
		</div>
	</div>
</div>